/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAccordion: typeof import('./components/UiAccordion/components/UiAccordion.vue')['default']
    UiAccordionHeader: typeof import('./components/UiAccordion/components/UiAccordionHeader.vue')['default']
    UiAccordionItem: typeof import('./components/UiAccordion/components/UiAccordionItem.vue')['default']
    UiAccordionPanel: typeof import('./components/UiAccordion/components/UiAccordionPanel.vue')['default']
    UiTabLabel: typeof import('./components/UiTabs/components/UiTabLabel.vue')['default']
    UiTabList: typeof import('./components/UiTabs/components/UiTabList.vue')['default']
    UiTabListPanels: typeof import('./components/UiTabs/components/UiTabListPanels.vue')['default']
    UiTabPanel: typeof import('./components/UiTabs/components/UiTabPanel.vue')['default']
    UiTabs: typeof import('./components/UiTabs/components/UiTabs.vue')['default']
    UiTabsLabels: typeof import('./components/UiTabs/UiTabsLabels.vue')['default']
    UiTabsPanels: typeof import('./components/UiTabs/UiTabsPanels.vue')['default']
  }
}
